flowchart TD
    A(("Начало")) --> B[/"Ввод points"/]
    B --> C{"8 <= points.size <= 12"}
    C -->|"Нет"| D["throw IllegalArgumentException"]
    C -->|"Да"| E{"2 <= degree <= 3"}
    E -->|"Нет"| F["throw IllegalArgumentException"]
    E -->|"Да"| G[" matrix = Array(degree + 1) { DoubleArray(degree + 2) }"]
    G --> H{{"0 <= i <= degree"}}
    H -->|"i <= degree"| I["matrix[i][j] = points.sumOf { it.x.pow(i + j) }"]
    I --> J["i++"]
    J --> H
    H -->|"i > degree"| K[" coefficients = solveGauss(matrix)"]
    K --> M[" meanSquareError = calculateMeanSquareError(points, function)\n deviation = calculateDeviation(points, function)\n determinationCoefficient = calculateDeterminationCoefficient(points, function)"]
    M --> N["Возврат ApproximationResult"]
    N --> O(("Конец"))