flowchart TD
    A(("Начало")) --> B[/"Ввод points"/]
    B --> C{"8 <= points.size <= 12"}
    C -->|"Нет"| D["throw IllegalArgumentException"]
    C -->|"Да"| E[" transformedPoints = points.map { Point(ln(it.x), ln(it.y)) }"]
    E --> F[" sumLnX = transformedPoints.sumOf { it.x }\n sumLnY = transformedPoints.sumOf { it.y }\n sumLnXLnY = transformedPoints.sumOf { it.x * it.y }\n sumLnX2 = transformedPoints.sumOf { it.x * it.x }"]
    F --> G[" determinant = sumLnX2 * n - sumLnX * sumLnX"]
    G --> H[" b = (sumLnXLnY * n - sumLnX * sumLnY) / determinant\n lnA = (sumLnX2 * sumLnY - sumLnX * sumLnXLnY) / determinant"]
    H --> I[" a = exp(lnA)"]
    I --> J[" function = { x -> a * x.pow(b) }"]
    J --> K[" meanSquareError = calculateMeanSquareError(points, function)\n deviation = calculateDeviation(points, function)\n determinationCoefficient = calculateDeterminationCoefficient(points, function)"]
    K --> L["ApproximationResult"]
    L --> M(("Конец"))
